### ISSUE TITLE
[question][appreciation] Issues running dev server

### ISSUE THREAD

**Issue by angelhdzmultimedia** [arashsheyda/nuxt-fullstack#2]
Hello! 👋🔥💚 nice project!!!

Had fun 🔎spying on the source code.
Had a laugh 🤣 with the `jose` package. `José` is a common name in the spanish-speaking regions.

But can't run the dev server!
![image](https://github.com/arashsheyda/nuxt-fullstack/assets/10191085/d62f195a-ae3b-4797-9392-f971296cecfb)

```

 WARN  [Vue Router warn]: uncaught error during route navigation:


 ERROR  Cannot find module './dist'
Require stack:
- C:\Users\AngelHdz\Documents\Programming\TypeScript\projects\nuxt-mongoose-fullstack\nuxt-fullstack\mdast-util-from-markdown

  Require stack:
  - mdast-util-from-markdown
  at Function._resolveFilename (node:internal/modules/cjs/loader:1143:15)
  at Function._load (node:internal/modules/cjs/loader:984:27)
  at Module.require (node:internal/modules/cjs/loader:1231:19)
  at require (node:internal/modules/helpers:179:18)
  at mdast-util-from-markdown:3:18
  at ViteNodeRunner.runModule (/C:/Users/AngelHdz/Documents/Programming/TypeScript/projects/nuxt-mongoose-fullstack/nuxt-fullstack/node_modules/vite-node/dist/client.mjs:362:11)
  at ViteNodeRunner.directRequest (/C:/Users/AngelHdz/Documents/Programming/TypeScript/projects/nuxt-mongoose-fullstack/nuxt-fullstack/node_modules/vite-node/dist/client.mjs:346:16)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async ViteNodeRunner.cachedRequest (/C:/Users/AngelHdz/Documents/Programming/TypeScript/projects/nuxt-mongoose-fullstack/nuxt-fullstack/node_modules/vite-node/dist/client.mjs:189:14)
  at async ViteNodeRunner.dependencyRequest (/C:/Users/AngelHdz/Documents/Programming/TypeScript/projects/nuxt-mongoose-fullstack/nuxt-fullstack/node_modules/vite-node/dist/client.mjs:233:12)


 WARN  [nuxt] Failed to stringify dev server logs. You can define your own reducer/reviver for rich types following the instructions in https://nuxt.com/docs/api/composables/use-nuxt-app#payload. Cannot stringify arbitrary non-POJOs

  at flatten (/C:/Users/AngelHdz/Documents/Programming/TypeScript/projects/nuxt-mongoose-fullstack/nuxt-fullstack/node_modules/devalue/src/stringify.js:138:13)
  at flatten (/C:/Users/AngelHdz/Documents/Programming/TypeScript/projects/nuxt-mongoose-fullstack/nuxt-fullstack/node_modules/devalue/src/stringify.js:102:15)
  at flatten (/C:/Users/AngelHdz/Documents/Programming/TypeScript/projects/nuxt-mongoose-fullstack/nuxt-fullstack/node_modules/devalue/src/stringify.js:166:43)
  at flatten (/C:/Users/AngelHdz/Documents/Programming/TypeScript/projects/nuxt-mongoose-fullstack/nuxt-fullstack/node_modules/devalue/src/stringify.js:102:15)
  at stringify (/C:/Users/AngelHdz/Documents/Programming/TypeScript/projects/nuxt-mongoose-fullstack/nuxt-fullstack/node_modules/devalue/src/stringify.js:178:16)
  at <anonymous> (node_modules\nuxt\dist\core\runtime\nitro\dev-server-logs.js:44:92)
  at /C:/Users/AngelHdz/Documents/Programming/TypeScript/projects/nuxt-mongoose-fullstack/nuxt-fullstack/node_modules/hookable/dist/index.mjs:48:66
  at /C:/Users/AngelHdz/Documents/Programming/TypeScript/projects/nuxt-mongoose-fullstack/nuxt-fullstack/node_modules/hookable/dist/index.mjs:48:56
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at <anonymous> (node_modules\nuxt\dist\core\runtime\nitro\renderer.js:301:3)

```

### Steps

- Clone repo
- Set `MONGODB_URI` in `~/.env`
- `bun install`
- `bunx nuxi upgrade -f`
- `bun run dev`

### Attempt to solve

- Installed `mdast-util-from-markdown@2.0.0` globally.

`~/package.json`
```ts
"devDependencies": {
    "@antfu/eslint-config": "^2.4.4",
    "@iconify-json/logos": "^1.1.40",
    "@iconify-json/ph": "^1.1.8",
    "@iconify-json/simple-icons": "^1.1.82",
    "@nuxt/ui": "^2.11.0",
    "@nuxt/ui-pro": "^0.5.0",
    "@nuxtjs/mdc": "^0.2.8",
    "@types/bcryptjs": "^2.4.6",
    "@types/jsonwebtoken": "^9.0.5",
    "@vueuse/nuxt": "^10.7.0",
    "bcryptjs": "^2.4.3",
    "defu": "^6.1.3",
    "eslint": "^8.55.0",
    "jose": "^5.1.3",
    "jsonwebtoken": "^9.0.2",
    "nuxt": "^3.11.2",
    "nuxt-mongoose": "^1.0.3",
    "ohash": "^1.1.3",
    "vue": "^3.3.11",
    "vue-router": "^4.2.5"
  }
```

**Comment by arashsheyda** [comment]
@angelhdzmultimedia hahah yes. I havn't tried with `bun` but I just cloned the repo and installed with `pnpm` and it works.

**Comment by angelhdzmultimedia** [comment]
> @angelhdzmultimedia hahah yes. I havn't tried with `bun` but I just cloned the repo and installed with `pnpm` and it works.

K, k. Gonna try with pnpm, thank you, hope you're having a nice Sunday. 👋🔥💚

**Comment by angelhdzmultimedia** [comment]
Wellp.... cloned the repo again, `pnpm install && pnpm run dev`. Same error 😭

**Edit:** Installed `mdast-util-from-markdown` with `pnpm` globally. Still error.

**Edit 2:** I have Node `20.12.0.` Maybe that's it?

**Edit 3:**
![image](https://github.com/arashsheyda/nuxt-fullstack/assets/10191085/313eb629-76de-47f7-84be-9fa8833d0845)

**Edit 4:** Do you run `pnpx nuxi upgrade -f`?

**Comment by angelhdzmultimedia** [comment]
This is a different error when I run `pnpx nuxi upgrade -f` to upgrade nuxt to latest version:

![image](https://github.com/arashsheyda/nuxt-fullstack/assets/10191085/dc552829-d1ef-4136-9ed3-d390432ca41c)

**Comment by arashsheyda** [comment]
@angelhdzmultimedia I don't know 😅

**Comment by angelhdzmultimedia** [comment]
Ok closing.
